gems: 
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
public-title: Andrew Hoefling - Life Through Code
title: Andrew Hoefling
author: Andrew Hoefling
email: andrew@hoeflingsoftware.com
description: >
  A blog about software development with a focus on Microsoft 
  Technologies by Andrew Hoefling. Andrew Hoefling is a Lead 
  Software Engineer for Surge Consulting Company 
  (http://www.surgeforward.com/) and owns Hoefling Software
  (http://www.hoeflingsoftware.com/). 
description-visible: > # this means to ignore newlines until "baseurl:"
  My adventures through software development in the world of .NET.
  Blog posts will focus on a new issue, achievment or technology
  that I am currently working with. You will find how-to guides and
  recommendations through the blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.andrewhoefling.com" # the base hostname & protocol for your site
fullname: Andrew Hoefling
twitter: andrew_hoefling
github_username:  ahoefling
stackoverflow_name: andrew-hoefling
linkedin_user: andrew-hoefling-38324912
social:
  name: Andrew Hoefling
  links:
    - https://github.com/ahoefling
    - https://www.linkedin.com/in/andrew-hoefling-38324912
    - https://plus.google.com/+AndrewHoefling
    - https://twitter.com/andrew_hoefling
    - https://www.facebook.com/windpants
# Build settings
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-architect