# Site settings
title: Andrew Hoefling - Life Through Code
email: andrew@hoeflingsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures through software development in the world of .NET.
  Blog posts will focus on a new issue, achievment or technology
  that I am currently working with. You will find how-to guides and
  recommendations through the blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.andrewhoefling.com" # the base hostname & protocol for your site
fullname: Andrew Hoefling
twitter_username: ahoefling
github_username:  ahoefling
stackoverflow_name: andrew-hoefling
linkedin_user: andrew-hoefling-38324912

# Build settings
markdown: kramdown

gems:
    - jekyll-seo-tag
