# Site settings
title: Andrew Hoefling's Development Blog
email: andrew@hoeflingsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures through software development in the world of .NET.
  Blog posts will focus on a new issue, achievment or technology
  that I am currently working with. You will find how-to guides and
  recommendations through the blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ahoefling.github.io" # the base hostname & protocol for your site
twitter_username: ahoefling
github_username:  ahoefling

# Build settings
markdown: kramdown
